server:
  port: 5003
  servlet:
    context-path: /WeBASE-Transaction

spring:
  # 数据库连接，需和WeBASE-Chain-Manager服务相同
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webasechainmanager?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: "defaultAccount"
    password: "defaultPassword"

constant: 
  ## WeBASE-Sign签名服务ip端口
  signServer: 127.0.0.1:5004

  ## front request
  httpTimeOut: 5000
  contractDeployTimeOut: 30000
  maxRequestFail: 3
  sleepWhenHttpMaxFail: 60000
  frontGroupCacheClearTaskCron: 0 0 1 * * ? 
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.webank.webase.transaction.repository.bean
  
logging: 
  config: classpath:log/log4j2.xml
  level:
    com.webank.webase.transaction: info
