server: 
  port: 8082
  context-path: /webase-transaction

spring: 
  datasource: 
    url: jdbc:mysql://10.0.0.1:3306/testDB?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis: 
  mapper-locations: classpath:mapper/*.xml

constant: 
  frontIpPorts: 10.0.0.1:8081
  cronTrans: 0/1 * * * * ?
  requestCountMax: 6
  selectCount: 10
  intervalTime: 600
  sleepTime: 50

thread: 
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 500
  keepAlive: 60

logging: 
  config: classpath:log4j2.xml