server:
  port: 5003
  servlet:
    context-path: /WeBASE-Transaction

sdk:
  # 机构名
  orgName: webank
  timeout: 10000
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100
  keepAlive: 60
  # 切换非国密与国密 0: standard, 1: guomi
  encryptType: 0
  # 链信息，可配置多链（多链需同时为非国密或时同为国密，对应sdk.encryptType）
  chainConfigList:
  - chainId: 1
    # 群组信息，可配置多群组和多节点
    groupConfig:
      # 复制对应非国密或国密证书
      caCert: classpath:cert/ca.crt
      sslCert: classpath:cert/node.crt
      sslKey: classpath:cert/node.key
      gmCaCert: classpath:cert/gmca.crt
      gmSslCert: classpath:cert/gmsdk.crt
      gmSslKey: classpath:cert/gmsdk.key
      gmEnSslCert: classpath:cert/gmensdk.crt
      gmEnSslKey: classpath:cert/gmensdk.key
      allChannelConnections:
      - groupId: 1
        connectionsStr:
        - 127.0.0.1:20200
        - 127.0.0.1:20201
      - groupId: 2
        connectionsStr:
        - 127.0.0.1:20200
        - 127.0.0.1:20201

constant: 
  # WeBASE-Sign签名服务ip端口
  signServer: 127.0.0.1:5004

logging: 
  config: classpath:log4j2.xml
